server:
  port: 8080
spring:
  application:
    name: "InvoiceManagement"
  devtools:
    add-properties: false
  webflux:
    base-path: /ms_invoice_management
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  adapter:
    postgres:
      database: ${DB_POSTGRES:invoice_reactive}
      schema: ${DB_POSTGRES_SCHEMA:public}
      host: ${DB_POSTGRES_HOST:localhost}
      port: ${DB_POSTGRES_PORT:5432}
      username: ${DB_POSTGRES_USER:admin}
      password: ${DB_POSTGRES_PASS:secret}
      pool:
        initial-size: 12
        max-size: 15
        max-idle-time: 10

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: secret123
  queue: audit-queue  # Nombre de la cola
  exchange: audit-exchange  # Exchange directo para simplicidad
  routing-key: audit-key

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
